### ISSUE TITLE
Feature request : Multiplayer & bots

### ISSUE THREAD

**Issue by William-LP** [Lamiette/Random-game#1]
Hi,

First of all thanks for this amazing game you're working on.

I wish I could play that game with few friends and bots to make it a bit more challenging.

Is it something you're planning to implement in the future? If yes any due date?

Thanks !

**Comment by Lamiette** [comment]
Hi Bro,

I confirm, this is all planned, I just need time and some more skills to do
that.
I will keep you informed about any further update on my game.

Thanks for all your support, you're the number one, never forget.

Bisous

**Comment by William-LP** [comment]
```python
import random

floor = 0
roof = 101

nbr_to_guess =  random.randint(floor,roof)
bot_guess = random.randint(floor,roof)

while bot_guess != nbr_to_guess :
    if bot_guess < nbr_to_guess : 
        print("Bot tried : " + str(bot_guess))
        print("Higher !")
        floor = bot_guess
        bot_guess = random.randint(floor,roof)
    else :
        print("Bot tried : " + str(bot_guess))
        print("Lower !")
        roof = bot_guess
        bot_guess = random.randint(floor,roof)
print("gg, number was " + str(nbr_to_guess))
```

**Comment by Lamiette** [comment]
Hi bro,

I've updated my game.

It is not perfect ( of course ) but you can know play against as many friends as you want and add one bot.
I'm working on additional bots but I need to learn more on the toile.
I'm actually trying to add a leaderboard too.

Any request is accepted to improve my game.

Regards / Bisous

**Comment by Lamiette** [comment]
Job is done
